Repository titaniumnetwork-dev/Aurora, pull requests merged in 2020-12, with the labels that each got.

#1 Added .editorconfig to fix web viewer problems
  .editorconfig
Labels: enhancement

#5 Add go modules.
  go.mod
Labels: enhancement

#6 Added proxy functionality in proxy.go and main.go
  main.go
  proxy/proxy.go
Labels: enhancement

#7 Added transport control to http client in proxy.go
  proxy/proxy.go
Labels: enhancement

#9 Removed unneeded code from proxy.go
  proxy/proxy.go
Labels: enhancement

#12 Added proper url parsing in proxy.go
  proxy/proxy.go
Labels: bug, enhancement

#13 Modified README.md for more clarification
  README.md
Labels: documentation
